source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'JiaJIaShunTestDemo' do

pod 'BaiduMapKit' #百度地图SDK

pod 'MJExtension'

pod 'AFNetworking'

pod 'Masonry'

end

